# ===================================================================================================
#
# Beschrijving:
#   DIG_Mobile-BuildAll-pipeline.yml
#
# ===================================================================================================


trigger:
  batch: true
  branches:
    include:
     - master
     - main
     - TST
     - ACC
     - PP
     - PROD

#
# Gebruik een MS-Hosted machine
pool:
  vmImage: 'macOS-latest'

variables:
  #
  # Algemene instellingen
  cfg_Debug                    : "false"

  #
  # Sonarcloud connection details
  cfg_SonarConnectionName      : "BDMCC SonarCloud connection"
  cfg_SonarProjectName         : "$(System.TeamProject)"
  cfg_SonarKey                 : "DIG_Mobile"  

  #
  # AppCenter connections details
  cfg_AppCenterConnectionName  : "BDMCC AppCenter connection"

resources:
  #
  # self:     Als je repostitory resources gebruikt, dan moet je 'self' expliciet ook uit checken!
  # repo_tpl: Standaard repo met pipeline templates en scripts includen in deze pipeline
  repositories:
  - repository: self
  - repository: repo_tpl
    type: git
    name: "MCC - Ontwikkelstraat/MCC-PipelineTemplatesScripts"
    ref: "productie"
                               
steps:
#
# Zie ook: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout
- checkout: self
  submodules: true
  persistCredentials: true  
  path: src

#
# Deze repo bevat alle pipeline templates en noodzakelijke scripts
- checkout: repo_tpl
  path: tpl

#
# 'mcc-build-all.yml' is de start template voor het builden van MCC Apps.
- template: tpl/mcc-build-all.yml@repo_tpl
  parameters:    
      DBG: ${{ variables['cfg_Debug'] }}      

#
# Pipeline done.
